DELIVERY_METHOD_DELIVERY = 'delivery'
DELIVERY_METHOD_COLLECTION = 'collection'

DELIVERY_METHOD_CHOICES = [
    (DELIVERY_METHOD_COLLECTION, 'Collection'),
    (DELIVERY_METHOD_DELIVERY, 'Delivery'),
]
