# Generated by Django 5.1.9 on 2025-06-13 16:49

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('description', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('prepare', models.CharField(blank=True, help_text='Preparation time', max_length=100)),
                ('cook', models.CharField(blank=True, help_text='Cooking time', max_length=100)),
                ('serves', models.CharField(blank=True, help_text='Number of servings', max_length=100)),
                ('ingredients', wagtail.fields.RichTextField(blank=True)),
                ('method', wagtail.fields.RichTextField(blank=True)),
                ('recipe_tips', wagtail.fields.RichTextField(blank=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now, verbose_name='Date Posted')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RecipePageTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
