# Generated by Django 5.1.9 on 2025-06-13 16:49

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('products', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='products.category'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='dietary_options',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='recipes', to='products.dietaryoption'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='recipeindex',
            name='featured_recipe',
            field=models.ForeignKey(blank=True, help_text='Featured recipe to display on the Recipes Index page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.recipepage'),
        ),
        migrations.AddField(
            model_name='recipepagetags',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.recipepage'),
        ),
        migrations.AddField(
            model_name='recipepagetags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.RecipePageTags', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
