# Generated by Django 5.1.9 on 2025-05-26 09:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeindex',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
