# Generated by Django 5.1.9 on 2025-06-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeindex',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='summary',
        ),
    ]
