# Generated by Django 5.1.9 on 2025-05-26 10:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_recipeindex_description'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('prepare', models.CharField(blank=True, help_text='Preparation time', max_length=100)),
                ('cook', models.CharField(blank=True, help_text='Cooking time', max_length=100)),
                ('serves', models.CharField(blank=True, help_text='Number of servings', max_length=100)),
                ('dietary_info', models.CharField(blank=True, help_text='Dietary information (e.g., vegan, gluten-free)', max_length=100)),
                ('ingredients', wagtail.fields.RichTextField(blank=True)),
                ('method', wagtail.fields.RichTextField(blank=True)),
                ('recipe_tips', wagtail.fields.RichTextField(blank=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
