# Generated by Django 5.1.9 on 2025-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='summary',
            field=models.CharField(blank=True, help_text='A brief summary of the recipe', max_length=255),
        ),
    ]
