# Generated by Django 5.1.9 on 2025-05-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipepage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeindex',
            name='featured_recipe',
            field=models.ForeignKey(blank=True, help_text='Featured recipe to display on the Recipes Index page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.recipepage'),
        ),
    ]
