# Generated by Django 5.1.9 on 2025-06-01 20:30

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_recipepagetags_recipepage_tags'),
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='dietary_info',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='dietary_options',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Dietary options applicable to this recipe', related_name='recipes', to='products.dietaryoption'),
        ),
    ]
