# Generated by Django 5.1.9 on 2025-06-01 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_recipepage_dietary_info_and_more'),
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the recipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='products.productcategory'),
        ),
    ]
