# Generated by Django 5.1.9 on 2025-06-02 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_recipepage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepage',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date when the recipe was posted.', verbose_name='Date Posted'),
            preserve_default=False,
        ),
    ]
