# Generated by Django 5.1.9 on 2025-06-02 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_recipepage_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when the recipe was posted.', verbose_name='Date Posted'),
        ),
    ]
