# Generated by Django 5.1.9 on 2025-06-04 11:15

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_recipepage_date_posted'),
        ('products', '0014_rename_productcategory_category'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='products.category'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='dietary_options',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='recipes', to='products.dietaryoption'),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.RecipePageTags', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
