# Generated by Django 5.1.8 on 2025-04-30 10:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 3), ('about_section', 6), ('gallery', 8), ('contact_section', 12), ('opening_hours', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.StructBlock', [[('svg_icon', 2), ('title', 0), ('description', 1)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 0), ('description', 1), ('features', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (2,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('svg_icon', 0), ('contact_text', 0)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'max_num': 3}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 9), ('contacts', 11)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')]}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 5pm - 10pm'}), 15: ('wagtail.blocks.StructBlock', [[('day', 13), ('hours', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'max_num': 7}), 17: ('wagtail.blocks.StructBlock', [[('entries', 16)]], {})}),
        ),
    ]
