# Generated by Django 5.1.9 on 2025-06-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svgicon',
            options={'verbose_name': 'SVG Icon', 'verbose_name_plural': 'SVG Icons'},
        ),
    ]
