# Generated by Django 5.1.8 on 2025-04-30 10:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_about1_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about1_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about1_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about2_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about2_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about2_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_sections',
            field=wagtail.fields.StreamField([('about_section', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'SVG path or class'}), 4: ('wagtail.blocks.StructBlock', [[('svg_icon', 3), ('title', 1), ('description', 2)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('features', 5)]], {})}, verbose_name='About Sections'),
        ),
        migrations.DeleteModel(
            name='AboutFeature',
        ),
    ]
