# Generated by Django 5.1.9 on 2025-07-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_svgicon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Inbox'},
        ),
    ]
