# Generated by Django 5.1.8 on 2025-04-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_about1_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='contact_subtitle',
        ),
    ]
