# Generated by Django 5.1.8 on 2025-05-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_contact_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvgIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(help_text='Upload SVG file only.', upload_to='icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='svg_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.svgicon'),
        ),
    ]
