# Generated by Django 5.1.8 on 2025-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_svgicon_alter_contactmethod_svg_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgicon',
            name='file',
        ),
        migrations.AddField(
            model_name='svgicon',
            name='icon',
            field=models.TextField(default='', help_text='Paste full inline SVG code here.'),
            preserve_default=False,
        ),
    ]
