# Generated by Django 5.1.8 on 2025-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contactmethod_id_alter_galleryimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Optional. Used only if uploaded image is not provided.'),
        ),
    ]
