# Generated by Django 5.1.8 on 2025-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_openinghour_options_openinghour_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmethod',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
