# Generated by Django 5.1.8 on 2025-05-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_contactmethod_options_contactmethod_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
