# Generated by Django 5.1.9 on 2025-06-11 11:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactsubmission_delete_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_sections',
            field=wagtail.fields.StreamField([('about_section', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [(1, 'soup'), (2, 'sandwich'), (3, 'salad'), (4, 'cake'), (5, 'ice-cream-bowl'), (6, 'ice-cream-cone'), (7, 'telephone'), (8, 'email'), (9, 'location')], 'help_text': 'Select an SVG icon', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('svg_icon', 3), ('title', 1), ('description', 2)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('features', 5)]], {})}, verbose_name='About Sections'),
        ),
    ]
