# Generated by Django 5.1.9 on 2025-06-12 08:54

import home.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_about_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_sections',
            field=wagtail.fields.StreamField([('about_section', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', (home.models.SvgIcon,), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('svg_icon', 3), ('title', 1), ('description', 2)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'max_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('features', 5)]], {})}, verbose_name='About Sections'),
        ),
    ]
