# Generated by Django 5.1.9 on 2025-06-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_about_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('address', 'Address')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
