# Generated by Django 5.1.9 on 2025-06-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_delivery', models.BooleanField(default=True)),
                ('allow_pickup', models.BooleanField(default=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=5.0, help_text='Charge for delivery service', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
