# Generated by Django 5.1.9 on 2025-06-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_storesettings_alter_order_email_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Store Settings', 'verbose_name_plural': 'Store Settings'},
        ),
    ]
