# Generated by Django 5.1.9 on 2025-07-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storesettings',
            old_name='allow_pickup',
            new_name='allow_collection',
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='delivery_method',
            field=models.CharField(choices=[('collection', 'Collection'), ('delivery', 'Delivery')], max_length=10),
        ),
    ]
