# Generated by Django 5.1.9 on 2025-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_allow_pickup_storesettings_allow_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
