# Generated by Django 5.1.9 on 2025-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Out for Delivery'), ('delivered', 'Delivered'), ('collected', 'Collected')], default='pending', max_length=20),
        ),
    ]
