# Generated by Django 5.1.9 on 2025-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='delivery_method',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('collection', 'Collection')], max_length=10),
        ),
    ]
