# Generated by Django 5.1.9 on 2025-07-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_deliverydetail_delivery_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreSettings',
        ),
    ]
