# Generated by Django 5.1.9 on 2025-05-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
