# Generated by Django 5.1.9 on 2025-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryoption',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
