# Generated by Django 5.1.9 on 2025-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_dietaryoption_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryoption',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
