# Generated by Django 5.1.9 on 2025-05-29 06:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_dietary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
