# Generated by Django 5.1.9 on 2025-05-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dietary_options',
            field=models.ManyToManyField(related_name='products', to='products.dietaryoption'),
        ),
    ]
