# Generated by Django 5.1.9 on 2025-05-29 09:07

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_dietary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dietary_options',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='products', to='products.dietaryoption'),
        ),
    ]
