# Generated by Django 5.1.9 on 2025-05-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_dietary_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryoption',
            name='colour',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('purple', 'Purple'), ('gray', 'Gray')], default='gray', max_length=20),
        ),
    ]
