# Generated by Django 5.1.9 on 2025-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_dietaryoption_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryoption',
            name='colour',
            field=models.CharField(choices=[('#e7000b', 'Red'), ('#5ea500', 'Green'), ('#ff8904', 'Orange'), ('#51a2ff', 'Blue'), ('#c27aff', 'Purple'), ('#99a1af', 'Gray')], default='gray', max_length=20),
        ),
    ]
