# Generated by Django 5.1.9 on 2025-06-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_recipepage_category'),
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
